#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: restrict-reconciliation
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-apps
#  namespace: Overwritten by 'targetNamespace'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-app-reconciler
#  namespace: Overwritten by 'targetNamespace'
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flx-app-reconciler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux-app-reconciler
subjects:
- kind: ServiceAccount
  name: flux-apps
#  namespace: Overwritten by 'targetNamespace'
