---
apiVersion: v1
kind: Namespace
metadata:
  name: restrict-reconciliation
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: restriction-sa
  namespace: restrict-reconciliation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restriction-role
  namespace: restrict-reconciliation
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restriction-rolebinding
  namespace: restrict-reconciliation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: restriction-role
subjects:
- kind: ServiceAccount
  name: restriction-role
  namespace: restrict-reconciliation
